version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app1:
    build: ./app
    container_name: app1
    depends_on:
      - redis
    command: ["node", "server.js"]

  app2:
    build: ./app
    container_name: app2
    depends_on:
      - redis
    command: ["node", "server.js"]

  worker:
    build: ./app
    container_name: db_worker
    depends_on:
      - mongo
      - redis
    command: ["node", "worker.js"] # This runs the background process instead of the web server

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "4002:80" # Exposed on 4002 for the Queue Test
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

volumes:
  mongo_data: